FROM node:22-alpine

WORKDIR /app

COPY frontend/package*.json ./
RUN npm install

COPY frontend/ .

RUN npm run build

# Install a simple static file server
RUN npm install -g serve

CMD ["serve", "-s", "dist", "-l", "3000"]
