FROM python:3.10-slim

WORKDIR /app

# Install system dependencies (for Playwright and general)
RUN apt-get update && apt-get install -y \
    wget \
    gnupg \
    && rm -rf /var/lib/apt/lists/*

COPY . .
RUN pip install .

RUN apt-get update --fix-missing && \
    playwright install-deps && \
    playwright install chromium

CMD ["uvicorn", "backend.api.main:app", "--host", "0.0.0.0", "--port", "8000"]
